spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
    password: class
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jdbc
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
    show-sql: true
